password = "Kiwy"

# Une clé pour chiffrer le contenu du cookie
cookie_encrypt_password = "UN_VAUT_MIEUX_QUE_ZERO"

# La valeur secrète qui sera stockée dans le cookie pour confirmer l'authentification
auth_secret_value = "02310265425"